### ISSUE TITLE
Feature request - Configure Rotation speed

### ISSUE THREAD

**Issue by ComedyTomedy** [loonywizard/js-confetti#30]
I'd like to be able to configure rotation somehow - ideally through a single variable `rotationSpeed`. 

I noticed in consts

    const MIN_INITIAL_ROTATION_SPEED = 0.03
    const MAX_INITIAL_ROTATION_SPEED = 0.07

Perhaps the min and max could be calculated from a single config value, for example if it had an initial value of r=0.05, MIN would be r\*0.6, and MAX r\*1.4.

Just a suggestion ☺ Thanks for your hard work making this.

**Comment by loonywizard** [comment]
Hi! thanks for feature request, could you please make PR? you can add `initialRotationSpeed` to `IAddConfettiConfig` and then use it in ConfettiShape

Also, very good idea to have MIN  initialRotationSpeed * 0.6, and MAX initialRotationSpeed * 1.4
we sure can create a constant MIN_INITIAL_ROTATION_SPEED = 0.05
and MIN would be `0.05 * X = 0.03`, MAX would be `0.05 * Y = 0.07`. `X = 0.6; Y = 1.4`

MIN and MAX should be calculated in ConfettiShape constructor, since we use variable here

**Comment by ComedyTomedy** [comment]
OK, I've made the necessary changes, but I have *no* idea how to test it, or even compile / run typescript, in fact.

I switched to a different branch & installed webpack, webpack-cli, and typescript. At this point I'm stuck.

I could just submit a PR in its current state, of course. I can't see why it wouldn't be correct, it's a simple change ☺

**Comment by loonywizard** [comment]
Sorry, my bad, I forgot to add instructions for running project locally (I have just added this section to README)

to run this locally:
Install dependencies by Yarn or NPM
```
yarn install
```

Run dev script with example build
```
yarn run dev
```

If you have any problems running library locally, please let me know here in this issue ☺

**Comment by ComedyTomedy** [comment]
Thanks for all your help with this! I tried and failed - I think because I'm unfamiliar with Typescript & not used to understanding other peoples' code.
